sudo: required
language: generic

services:
  - docker 

before_install:
  - dokcer build -t salmane/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true salmane/docker-react npm run test
